### ISSUE TITLE
Capitalized url's turned to lowercase

### ISSUE THREAD

**Issue by jessedobbelaere** [spatie/crawler#1]
Related to Spatie http-status-check tool. I ran the http-status-check scanner and I got an awful lot of 404's. Turns out  all the used url's are lowercase, while the assets in my cms use capitalized folders.

* This is the actual url for my asset (works, 200): `http://www.domain.be/src/Frontend/Files/userfiles/images/test.jpg`
* This url is used in the crawler/http-status-code scanner and does not work (error 404):  `http://www.domain.be/src/frontend/files/userfiles/images/test.jpg`

Any idea why all the used url's are lowercase? Otherwise great tool :+1:

**Comment by freekmurze** [comment]
I've made the crawler case sensitive in the master branch. Will have to do some tests, but if all is good, I'll tag it as a new version soon.

**Comment by jessedobbelaere** [comment]
Thanks, great! :+1:

**Comment by freekmurze** [comment]
v.1.0.1 is case sensitive. If you've installed the http-status-check-tool globally you can update it with `composer global update`.
