### ISSUE TITLE
How would one go about implementing craw limits per url format?

### ISSUE THREAD

**Issue by mocanuga** [spatie/crawler#106]
Hello,

I'm trying to implement this throttling feature, but i seem to get stuck.
How do I force the crawler to ignore URL's by format if it has crawled beyond a set limit?

Eg. If the URL is like /param1/param2 how do I make it ignore crawling same URLS again?

**Comment by freekmurze** [comment]
By default the crawler will not crawl urls more than once.

**Comment by mocanuga** [comment]
Thanks for the reply.

I want to scan the first 3 items on some category and then skip that category.

**Comment by freekmurze** [comment]
You can do this by creating your own `CrawlProfile`: https://github.com/spatie/crawler#filtering-certain-urls.

In should crawl you should return `true` when the crawler should crawl the link and `false` if it shouldn't. You can add any logic you want to that class.

**Comment by mocanuga** [comment]
I added another hook to prevent adding more URL's to the queue after the limit is reached. I added a new method the CrawProfile class and called it in the addAllLinksToCrawlQueue method.

It appears to do the trick.

Thanks for your help.
