### ISSUE TITLE
Ignore `tel:` links

### ISSUE THREAD

**Issue by sebastiandedeyne** [spatie/crawler#11]
See spatie/laravel-link-checker#3

**Comment by ptondereau** [comment]
I've patched this issue, but I'm not sure this is a good way to detect a good scheme for URL: Indeed, there is a lot of scheme available, such as `skype:`, `steam:`, etc...

@sebastiandedeyne what do you think ?

**Comment by sebastiandedeyne** [comment]
`tel` is enough since it's a de facto standard scheme. `skype`, `steam` etc. are edge cases, if necessary, package users can always edit their crawl profiles.
