### ISSUE TITLE
Crawler should respect robots.txt

### ISSUE THREAD

**Issue by freekmurze** [spatie/crawler#114]
Right now the crawler checks all links regardless of what's in the `robots.txt` file. Ideally the crawler should have a `respectRobotsTxt` method that parses the `robots.txt` file (or header) and only crawl the allowed links.

I'd accept a PR (with tests) that adds this to the package.

**Comment by danhunsaker** [comment]
Would it be acceptable to add a dependency on an external library that handles the parsing? If so, this would probably be a quick PR to put together, but if not, it seems important to know that in advance.

**Comment by freekmurze** [comment]
> Would it be acceptable to add a dependency on an external library that handles the parsing?

It would certainly be acceptable if that dependency has tests, good documentation and is maintained.

**Comment by brendt** [comment]
@danhunsaker Any specific packages coming to mind?

**Comment by danhunsaker** [comment]
Not particularly (I tend to do things in Laravel, so L5-specific packages are where my familiarity lies), but `webignition/robots-txt-file` seems solid. Others are simpler to use, but haven't been updated as recently, or don't have (enough) tests.

**Comment by sebastiandedeyne** [comment]
Don't forget there's a meta tag for robots values too

**Comment by brendt** [comment]
I'm working on this!

**Comment by Redominus** [comment]
meta tag for robtos already addressed in pull request  #139
