### ISSUE TITLE
proxy support

### ISSUE THREAD

**Issue by masihfathi** [spatie/crawler#128]
is it possible to use multi proxy and sth like rotating between ips for crawling?

**Comment by freekmurze** [comment]
I don't understand the question. Could you elaborate and give some code examples you'd which they worked?

**Comment by masihfathi** [comment]
i mean sth like this question:
https://stackoverflow.com/questions/28852057/change-ip-address-dynamically

**Comment by freekmurze** [comment]
Still don't exactly know what you want, but you can customize the behaviour of the underlying Guzzle client with middleware. Here's some info on that: https://medium.com/@brad_brothers/build-a-better-api-client-with-guzzle-middleware-2ace56868dc7

**Comment by nguyenhieptn** [comment]
When I crawl a large amount of data the server will prevent us with rate/limit and ip block. so I would like to change the user-agent and IP (proxy). Is there any strategy to do it at your code?

**Comment by phuclh** [comment]
> When I crawl a large amount of data the server will prevent us with rate/limit and ip block. so I would like to change the user-agent and IP (proxy). Is there any strategy to do it at your code?

Did you find any solution for that? Thank you!

**Comment by kesarawimal** [comment]
After spending a couple of days I found the solution, this may not be the exact solution but I thought it will be helpful for someone as I have landed here initially when I'm searching for the answer to "how to integrate proxy with spatie/crawler?".

This is how directly integrate a proxy with Guzzle:
`Crawler::create([RequestOptions::PROXY => 'http://34.206.72.140:80'])
                ->setCrawlObserver(new CustomCrawlObserver())
                ->ignoreRobots()
                ->setMaximumCrawlCount(1)
                ->setMaximumResponseSize(1024 * 1024 * 3)
                ->setParseableMimeTypes(['text/html', 'text/plain'])
                ->startCrawling($link);`

@freekmurze I think it will be usefully if you can add some reference to your readme about Request Options

https://docs.guzzlephp.org/en/stable/request-options.html#proxy
