### ISSUE TITLE
Crawler stops when encounter with 404 page.

### ISSUE THREAD

**Issue by zeleniy** [spatie/crawler#133]
When crawler encounter with 404 page it call `crawlFailed` method as mentoined in documentation, but it is also just exit (stop crawling). But i sure that it has a lot not visited links in its pool. So it seems it should work further (just skip that page/step) and continue to work. But it stops.

**Comment by freekmurze** [comment]
The tests prove that this functionality is working properly. Could you please PR a failing test?

**Comment by zeleniy** [comment]
Will do later
