### ISSUE TITLE
Impossible work with persistent queue

### ISSUE THREAD

**Issue by coodix** [spatie/crawler#137]
The issue is that it's impossible to pass to Crawler a Queue which work with persistent storage because Crawler saves state in memory in depthTree attribute.

If set a Queue which already has pending urls then after calling startCrawling Crawler fails with FatalError because depthTree is empty and new urls can't be attached to the tree.

**Comment by freekmurze** [comment]
Ping @systream

**Comment by Redominus** [comment]
Also url ids should be of type mixed instead of int to support things like UUID.

**Comment by freekmurze** [comment]
Feel free to PR fixes (be sure to include tests).

**Comment by systream** [comment]
@coodix Could you provide some more information about your implementation. I have a working PDO queue.

**Comment by coodix** [comment]
@systream , example of queue is here https://gist.github.com/coodix/d0a83fe284600b9183553ba1e5452cba

Problem appears on continuation of crawling. Fatal error is raised in Crawler::addAllLinksToCrawlQueue:

`$node = $this->addtoDepthTree($this->depthTree, $url, $foundOnUrl);
                
              if (! $this->shouldCrawl($node)) {
                    return;
                }`

addtoDepthTree return null. shouldCrawl accept  not nullable variable of Node class.

**Comment by Redominus** [comment]
The tree node is built in the Crawler class while the Queue is in its own class.
