### ISSUE TITLE
Provide Browsershot object or bodyHtml to CrawlObserver

### ISSUE THREAD

**Issue by kloor** [spatie/crawler#143]
Currently, Browsershot executes Javascript on a page after that page has been provided to a CrawlObserver. It would be useful if instead that execution could happen first, and either the Browsershot object or the bodyHtml from that object could be provided in some way to the observer.

**Comment by brendt** [comment]
This one should be fixed in 4.15: https://github.com/spatie/crawler/releases/tag/4.1.5
