### ISSUE TITLE
Crawler scans only one page with js execution enabled

### ISSUE THREAD

**Issue by radiocity** [spatie/crawler#157]
```php
Crawler::create()
    ->setCrawlObserver(new Logger())
    ->executeJavaScript()
    ->startCrawling($url);
```
Logger — an empty class without any logic and extended from CrawlObserver. 
Disabling javascript execution forces crawler scan myriad of pages normally. 
Does crawler can handle with external code such as `<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>`?

**Comment by freekmurze** [comment]
Under the hood we use Headless Chrome to exactue javascript. I'm pretty sure links like the one you mentioned will be processed.
