### ISSUE TITLE
[question] How does concurrent requests work indepth?

### ISSUE THREAD

**Issue by alpham8** [spatie/crawler#178]
Hi,

I am wondering on how your concurrent requests work indepth? I mean, do you use pthreads for it or just the GuzzleHttp based promises?

If the last one applies, could you please provide a second version of the project using the pthreads extension? I think that should really speed up your crawler.

Thanks in advice,

alpham8

**Comment by freekmurze** [comment]
We're using GuzzleHttp based promises. I don't have need for another version that use pthreads now. If you need that, you'll have to create it yourself. Feel free to fork our code.
