### ISSUE TITLE
I get an error while crawling

### ISSUE THREAD

**Issue by Starkmann** [spatie/crawler#179]
Type error: Argument 1 passed to Spatie\Crawler\Crawler::shouldCrawl() must be an instance of Tree\Node\Node, null given

The problem is in this snipped:
```
                $node = $this->addtoDepthTree($this->depthTree, $url, $foundOnUrl);

                if (! $this->shouldCrawl($node)) {
                    return;
                }

                if ($this->maximumCrawlCountReached()) {
                    return;
                }

                $crawlUrl = CrawlUrl::create($url, $foundOnUrl);

                $this->addToCrawlQueue($crawlUrl);
```
addtoDepthTree can return a null object. 

And then ```! $this->shouldCrawl($node)``` fails because of:

```protected function shouldCrawl(Node $node): bool``` not allowing null.

**Comment by freekmurze** [comment]
This is already fixed in the latest version. Pull it in with `composer update`.
