### ISSUE TITLE
Handlers extendability

### ISSUE THREAD

**Issue by Redominus** [spatie/crawler#180]
The new handlers for request fullfillment and failure are a really cool idea. The problem is that they are not easy to extend without also extending the Crawler class because they can not be passed as constructed objects.

Is there any reason why they should be instantiated every time a Pool is created?

Thanks for your amazing work. :smile:

**Comment by freekmurze** [comment]
I think that should be instantiated each time. 

I'd accept a PR with tests and updated docs that adds some setters to pass these objects from the outside.
