### ISSUE TITLE
maximumDepth not checked while respecting robots

### ISSUE THREAD

**Issue by MarcelWiebenga** [spatie/crawler#181]
The maximumDepth isn't checked while crawling with respect to robots. This might lead to issues when crawling large sites. The only way for me to get it to work is to use the 'ignoreRobots' function on the crawler, but then I won't be respecting the guidelines of the crawled site.

**Comment by freekmurze** [comment]
The tests seem to indicate that `maximumDepth` is being respected: https://github.com/spatie/crawler/blob/master/tests/CrawlerTest.php#L242-L287

Could you PR a failing test for us to look at?
