### ISSUE TITLE
 Class 'Spatie\Crawler' not found in

### ISSUE THREAD

**Issue by mcmc4519** [spatie/crawler#183]
When I try to use your package, I found errors: 

Warning: Class 'Tightenco\Collect\Support\Debug\Dumper' not found in vendor\tightenco\collect\src\Collect\Support\alias.php on line 18

Warning: Class 'Tightenco\Collect\Support\Debug\HtmlDumper' not found in vendor\tightenco\collect\src\Collect\Support\alias.php on line 18

 I use windows 10 x64, php 7.1

**Comment by freekmurze** [comment]
The tests in this package seem to indicate that everything is working fine. We don't use the dumper in our package, so I guess the error is caused by your application code.

Please submit a PR if there's something we need to change at our side.
