### ISSUE TITLE
How to load CrawlQueue saved in the database?

### ISSUE THREAD

**Issue by coolos17** [spatie/crawler#196]
Hi,

I have problems with loading old data from database to the custom CrawlQueue.

In Crawler I set setMaximumCrawlCount variable to 200 (this takes around 30s in my test site to grab links). When CrawlObserver call to finishedCrawling method, I save informations from CrawlQueue->urls implementation to the database. Then in next checking I load this data to the CrawlQueue->urls and CrawlQueue->pendingUrls, but this gives me often timeout (more then 60s). So I decided to load only last 200 urls from database to the CrawlQueue->urls and CrawlQueue->pendingUrls and rest of old data from database is checking in the CrawlProfile->shouldCrawl and return false if url exists in the database, but with this method I can only grab some small numbers of links with every checks (around 10).

Can you help me with this?

**Comment by freekmurze** [comment]
I can't help you with this specific case as it isn't really a problem with the package itself. 

Please post your problem on a public forum like stackoverflow.com

If the package is in error, please open up a new issue with a specific description (or a PR that fixes it)

**Comment by BenjaminHoegh** [comment]
> Hi,
> 
> I have problems with loading old data from database to the custom CrawlQueue.
> 
> In Crawler I set setMaximumCrawlCount variable to 200 (this takes around 30s in my test site to grab links). When CrawlObserver call to finishedCrawling method, I save informations from CrawlQueue->urls implementation to the database. Then in next checking I load this data to the CrawlQueue->urls and CrawlQueue->pendingUrls, but this gives me often timeout (more then 60s). So I decided to load only last 200 urls from database to the CrawlQueue->urls and CrawlQueue->pendingUrls and rest of old data from database is checking in the CrawlProfile->shouldCrawl and return false if url exists in the database, but with this method I can only grab some small numbers of links with every checks (around 10).
> 
> Can you help me with this?

Do you already have solved this? And can you share the code?
