### ISSUE TITLE
Should rel="next" and rel="prev" be crawled?

### ISSUE THREAD

**Issue by Redominus** [spatie/crawler#197]
This google [blogpost](https://webmasters.googleblog.com/2011/09/pagination-with-relnext-and-relprev.html) claims those two link tags should be used to refer to other parts of paginated content.
I think the crawler should crawl those two links.
What do you think about it?

**Comment by freekmurze** [comment]
If it's easy to implement and test, I'd probably accept a PR that adds this to the package.
