### ISSUE TITLE
Call to a member function willCrawl() on string

### ISSUE THREAD

**Issue by mahmod2000** [spatie/crawler#199]
Hi

When I want to open a URL using whit package, it always throw the below error:
Call to a member function willCrawl() on string

Could you check it?
thanks.

**Comment by freekmurze** [comment]
The tests seem to indicate that the package is working as intended. Could your PR a failing test for me to look at / fix?

**Comment by L00Cyph3r** [comment]
I had the same issue, this happens if you supply a reference instead of an instance.

This **doesn't** work:
```php
Crawler::create()->setCrawlObserver(CustomObserver::class)
```

This **does** work:
```php
Crawler::create()->setCrawlObserver(new CustomObserver)
```

Only way to make this foolproof is by checking the type on CrawlObserverCollection::__construct() instead of simply assigning it.

**Comment by rubenvanassche** [comment]
@mahmod2000 I think @L00Cyph3r has found the solution for your problem. You should always pass a constructed CustomObserver tot the `setCrawlObserver`method. 

We had a small discussion today if it would be useful to also make it possible to use the class name as the parameter. But this would not be useful if you use a constructor for `CrawlObserver`.
