### ISSUE TITLE
Does it support 5.5.9

### ISSUE THREAD

**Issue by fobus42** [spatie/crawler#2]
Hi, I'm not able to install it via composer because of PHP version depency, my PHP version is 5.5.9 it is really imposible to find a server that runs on PHP 5.6, does it work compatible with php 5.5* ?

Thanks

**Comment by freekmurze** [comment]
I lowered the requirements to php 5.5 in v1.0.2 of this package.

**Comment by fobus42** [comment]
Thanks a lot
