### ISSUE TITLE
use crawler to get info from the website

### ISSUE THREAD

**Issue by RabiCodie** [spatie/crawler#202]
Hi guys, 

thanks for this package and all packages you have built, we are building a small CRM for a client and want to implement the crawler to start generating leads through their domain / company website. what we want to achieve is to be able to type in the lead website and the web crawler will do the job and get us back data from the lead website : e.g company name - address - phone number - email address and even contact names of employees if they have a team section. is there any chance that the package could handle this, i could not find any info about this on the package page. 

many thanks 

cheers 👍

**Comment by freekmurze** [comment]
Take a look in the docs on how to create an observer. https://github.com/spatie/crawler#usage

This is a class that gets the response for every page crawled. You could parse the data you want from that response.

**Comment by ian-patel** [comment]
How about  return HTML in multi dimensions array?
