### ISSUE TITLE
Crawling becomes slow with large queues when maximumDepth is enabled

### ISSUE THREAD

**Issue by joaomisturini** [spatie/crawler#208]
While implementing a crawling system and using `setMaximumDepth(2)`, I noticed that the queue's execution started to become slower. As I digged into the code, I found out that the `foreach` used inside `addToDepthTree` method becomes increasingly slower as the implemented tree grows.

It is important to notice that the problem increases along with the tree size, and happens while searching the parent URL inside the tree. It is easier to reproduce when crawling large sites.

As I need a faster way to process the URL queue while keeping `setMaximumDepth(2)` set, I am willing to make a PR in the next couple weeks.

However, I am opening this issue because I am not shure yet what data structure to use to solve the problem. Also, I thought it was important to let this project's owners know about the incoming PR.

**Comment by freekmurze** [comment]
Thanks for the heads up. I welcome a PR that improves the performance. All current tests should pass. Closing this for now!
