### ISSUE TITLE
basic example of use

### ISSUE THREAD

**Issue by aicouto** [spatie/crawler#211]
I'm confused about which class should be extended exactly. would be easier to understand if there were a simple and complete example in the documentation.

**Comment by freekmurze** [comment]
This is the easiest way to use the crawler. The class you should extend is `\Spatie\Crawler\CrawlObserver`. The readme explains how you can configure a CrawlObserver.

```
use Spatie\Crawler\Crawler;

Crawler::create()
    ->setCrawlObserver(<class that extends \Spatie\Crawler\CrawlObserver>)
    ->startCrawling($url);
```

**Comment by aicouto** [comment]
yes, i have read the readme but  **<class that extends \Spatie\Crawler\CrawlObserver>** is a pseudo-code not a completly funcional basic example like found at **the php league's** by example.

**Comment by codolloR** [comment]
> yes @freekmurze , i have read the readme but **<class that extends \Spatie\Crawler\CrawlObserver>** is a pseudo-code not a completly funcional basic example like found at **the php league's** by example.

This helped me: https://laracasts.com/discuss/channels/laravel/instantiate-abstract-class?page=1#reply-481090

**Comment by aicouto** [comment]
@codolloR thank you very much ❤️

**Comment by ishutrehan** [comment]
How can I get all public urls of website using site url via crawl?

**Comment by aicouto** [comment]
@ishutrehan $url=$page['path']
```php
    public function finishedCrawling()
    {
        foreach ($this->pages as $page){
            $url=$page['path'];
        }
    }
```

**Comment by BestPluginsWordpress** [comment]
`<?php

namespace Spatie\MixedContentScanner;

use GuzzleHttp\Exception\RequestException;

use Psr\Http\Message\UriInterface;
use Psr\Http\Message\ResponseInterface;

use Spatie\Crawler\Crawler;
use Spatie\Crawler\CrawlObservers\CrawlObserver;

require_once 'vendor/autoload.php';

class Test extends CrawlObserver {
    public function willCrawl(UriInterface $url) { }

    public function crawled(UriInterface $url, ResponseInterface $response, ?UriInterface $foundOnUrl = null): void {
        $path = $url->getPath();
        $doc = new \DOMDocument();
        @$doc->loadHTML($response->getBody());
        $title = $doc->getElementsByTagName("title")[0]->nodeValue;

        echo "$title<br>$url<br><br>";
    }

    public function crawlFailed(UriInterface $url, RequestException $requestException, ?UriInterface $foundOnUrl = null): void { }

    public function finishedCrawling() { }
}

$url = 'https://github.com';
Crawler::create()
    ->setCrawlObserver(new Test())
    ->ignoreRobots()
    ->setConcurrency(3)
    ->acceptNofollowLinks()
    ->setMaximumCrawlCount(1)
    ->setDelayBetweenRequests(500)
    ->setParseableMimeTypes(['text/html'])
    ->startCrawling($url)
?>`
