### ISSUE TITLE
How to implement mixed-content-check with crawled urls

### ISSUE THREAD

**Issue by petericebear** [spatie/crawler#215]
Hi,

Is there way to implement the mixed content scanner within this method:
```php
    public function crawled(
        UriInterface $url,
        ResponseInterface $response,
        ?UriInterface $foundOnUrl = null
    ) {
        if (checkUrlForMixedContent($url)) {
            //something like this -> checkContentForMixedcontent($response)
        }
    }
```
The checkUrlForMixedContent($url) will be a private method to look into a database to see if the content needs to be checked for mixed content.

Hope you can help out. I did not found anything about this, or in the mixed-content package to check from already crawled source.

**Comment by freekmurze** [comment]
We have another package that does exactly the thing you're looking for: https://github.com/spatie/mixed-content-scanner

**Comment by petericebear** [comment]
I saw that package indeed, it leans on this package. I thought to extract that only functionality within this way. But I will look into that source-code to see if I can hook into it without scraping twice

**Comment by petericebear** [comment]
Got it working! Postcard on its way ;)
