### ISSUE TITLE
Maximum execution time of 30 seconds exceeded

### ISSUE THREAD

**Issue by BenjaminHoegh** [spatie/crawler#219]
Maximum execution time of 30 seconds exceeded in vendor/spatie/crawler/src/CrawlQueue/CollectionCrawlQueue.php on line 90

what does this mean? and how to change it?

**Comment by freekmurze** [comment]
This means that your PHP process has been shut down because it takes more than 30 seconds. Increase the allowed time. Google a bit for specific instructions for your system.
