### ISSUE TITLE
return crawl response data

### ISSUE THREAD

**Issue by Toe-Tet** [spatie/crawler#220]
Thank you for the package. I crawl the data and all the response is correct and everything is fine in MyCrawler class that extends CrawlerObserver. but, I don't know how to return that response data to the $data variable.

`$data = Crawler::create()
->executeJavaScript()
->setCrawlObserver(new MyCrawler())
->ignoreRobots()
->startCrawling($url);
// do something with $data
`

**Comment by freekmurze** [comment]
The `crawled` function of your observer will get the `$response` of each crawled url.

**Comment by kaianuar** [comment]
I know this is closed but I don't think the question was explained in full. I wanted to do the same thing as @Toe-Tet. Check out my gist here https://gist.github.com/kaianuar/ca1c447dcbd891e57c53b7c0c61c3bbc
