### ISSUE TITLE
composer installation not working

### ISSUE THREAD

**Issue by ishutrehan** [spatie/crawler#221]
When I run the command  "composer require spatie/crawler" it display the error

 - The requested package spatie/crawler No version set (parsed as 1.0.0) is satisfiable by spatie/crawler[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.
Please provide me solution for this

**Comment by freekmurze** [comment]
This error is not caused by the package, but probably by something in your environment.

**Comment by ishutrehan** [comment]
All other packages installed suucessfully. have you any idea where is the actual problem is?

**Comment by freekmurze** [comment]
Not really. If it turns out that our package caused this error, open up a new issue with instructions on how to reproduce, or submit a PR that fixed it.
