### ISSUE TITLE
dependency spatie/image-optimizer requiring php 7.2

### ISSUE THREAD

**Issue by PBrunot** [spatie/crawler#224]
I ran a php composer update on php 7.1 and it broke my build because I have spatie/crawler dependency (php ^7.0) which needs spatie/image-optimizer (php ^7.2).

**Comment by AdnanMoghal** [comment]
same problem here. Did you find any solution @PBrunot  ?

**Comment by PBrunot** [comment]
My workaround is to add an explicit version in the composer.json to reference the last spatie/image-optimizer using php7.0 (v1.1.4)

```
{
"spatie/crawler": "^4.0",
"spatie/image-optimizer": "1.1.4"
}
```
