### ISSUE TITLE
Crawl Resume 

### ISSUE THREAD

**Issue by zigwartybund** [spatie/crawler#226]
It would be awesome to add the ability to resume crawl after a shutdown. Maybe with a database logic to store crawl queue...and mark out witch links have already been crawled....

**Comment by freekmurze** [comment]
I don't need this myself, so I'm not going to invest time in it. If you need this and the code is simple, I'd accept a PR with tests that adds this to the package.

**Comment by zigwartybund** [comment]
Thanks for the reply...I Will try to add it myself then...
Le 5 juin 2019 20:57, "Freek Van der Herten" <notifications@github.com> a
écrit :

**Comment by Redominus** [comment]
What you need is a crawl frontier. You don't need to change the crawler. Implement a new CrawlQueue that uses a persistence mechanism and everytime you start the crawler check if there are pending urls, load them in the queue and pass it to the crawler. After crawling is done call some frontier clean method.

**Comment by repat** [comment]
@zigwartybund have a look at https://github.com/repat/spatie-crawler-redis
