### ISSUE TITLE
Operation timed out after 12916 milliseconds with 1392640 out of 2615063 bytes received

### ISSUE THREAD

**Issue by ash-25** [spatie/crawler#228]
Hello,  
I am getting this error for bigger websites with more than 10000 urls. any way to resolve this?

**Comment by Redominus** [comment]
As you can see in the message the connection reached the condifured timeout in the middle of the reception.
In the options array passed to ```Crawler::create($options)``` you should change the timeout option(in seconds) to a greater value. ```RequestOptions::TIMEOUT => 30,```.
