### ISSUE TITLE
External links to LinkedIn (company pages) returns HTTP status 999

### ISSUE THREAD

**Issue by baristacoder** [spatie/crawler#231]
Hi,

When a page finds a link to a LinkedIn page it gives errors like:
Unsuccessful request: `GET https://nl.linkedin.com/company/XXX` resulted in a `999 Request denied` response:

Does anyone know a way to give a status 200 for those kind of pages?
Not trying to build a LinkedIn scraper but more to see if an outgoing link is successful.

DuskBrowserTest seems to work on a blank Laravel project, but that will literally open up a chrome instance to go to an url.

**Comment by freekmurze** [comment]
They just deny access for crawlers. As I don't want this package to pretend it's not a crawler, I'll close this for now.

**Comment by michaelaguiar** [comment]
How do we get around the guzzlehttp error `Status code must be an integer value between 1xx and 5xx.` if it returns 999?

**Comment by michaelaguiar** [comment]
Never mind, `setCrawlProfile()` does the trick!
