### ISSUE TITLE
Lots of timeouts (cURL error 28) during crawl

### ISSUE THREAD

**Issue by BenMorel** [spatie/crawler#236]
I've been running the crawler for several hours on several websites, and all of them have A LOT of failures that lead to this `RequestException`:

> cURL error 28:  (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

I'm using a concurrency of `2` and no delay between requests, but overall the throughput is much less than 1 request / second.

I first thought that my IP was rate-limited by the target servers, that would drop incoming connections if their frequency exceeds a certain threshold, but the fact that it was happening on every single server intrigued me.

So while the crawler was running on a given host, I ran another script in parallel to query the same host, replicating the Guzzle config used by the Crawler:

```php
use GuzzleHttp\Client;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\RequestOptions;

$client = new Client();

for ($i = 0; $i < 20; $i++) {
    try {
        $client->get("https://www.example.com/", [
            RequestOptions::CONNECT_TIMEOUT => 10,
            RequestOptions::TIMEOUT => 10,
            RequestOptions::ALLOW_REDIRECTS => true,
        ]);
        echo 1;
    } catch (RequestException $e) {
        echo 0;
    }
}
```

To my surprise, this script only output `1`s, so all requests succeeded, while the crawler in another terminal was still getting cURL timeouts on 1/3 of the requests.

I tried with a shared instance of `Client` as well as a new instance in every iteration of the loop, same result.

**Does anyone have an idea of what could be causing these timeouts?**

**Comment by Redominus** [comment]
You are making syncronous requests. Try using asyncRequests.

**Comment by BenMorel** [comment]
Works fine with async requests, too:

```php
$client = new Client();

$promises = [];

for ($i = 0; $i < 20; $i++) {
    $promises[] = $client->getAsync("https://www.example.com/", [
        RequestOptions::CONNECT_TIMEOUT => 10,
        RequestOptions::TIMEOUT => 10,
        RequestOptions::ALLOW_REDIRECTS => true,
    ])->then(function(\Psr\Http\Message\ResponseInterface $response) {
        echo 1;
    }, function (RequestException $exception) {
        echo 0;
    });
}

Promise\settle($promises)->wait();
```

It quickly outputs `11111111111111111111` (it takes around 3s to complete 20 requests), while the Crawler in another terminal is still getting a lot of cURL errors 28.

**Comment by BenjaminHoegh** [comment]
Hey ben can you share your class? I'm trying to make a async crawler myself

**Comment by BenMorel** [comment]
As mentioned in #241, this issue only happens when using `setMaximumDepth()`: after a few hundred crawls, the recursive `addToDepthTree()` algorithm burns so much CPU that it does not check in with cURL often enough, leading to a cURL timeout.

Fixing #241 will fix this issue as well.

**Comment by freekmurze** [comment]
Closing this as the main cause is decribed in #241
