### ISSUE TITLE
exculde specified urls from crawling.

### ISSUE THREAD

**Issue by ash-25** [spatie/crawler#240]
Hi,
I am not allowed to modify robots.txt.
Is there a way other than robots.txt to specify a list of urls to be excluded from crawling.
appreciate any pointers and your time.

**Comment by BenMorel** [comment]
As explained in [the docs](https://github.com/spatie/crawler#filtering-certain-urls):

> You can tell the crawler not to visit certain urls by using the `setCrawlProfile`-function. That function expects an object that extends `Spatie\Crawler\CrawlProfile`:

```php
/*
 * Determine if the given url should be crawled.
 */
public function shouldCrawl(UriInterface $url): bool;
```

Please take the time to read the docs before opening an issue!
