### ISSUE TITLE
Crawling gets slower as the number of crawled pages raises

### ISSUE THREAD

**Issue by BenMorel** [spatie/crawler#241]
I've been experiencing very slow crawling after a few hundred pages.

To ensure that the problem did not come from the client-server connection, I used a [cache middleware](https://github.com/Kevinrob/guzzle-cache-middleware) with a [greedy cache strategy](https://github.com/Kevinrob/guzzle-cache-middleware#greedy-caching), and performed a dry run to store all the pages into the cache before doing any performance testing.

Here's a scatter plot of the time it takes to crawl a single page:

![crawl-time-plot](https://user-images.githubusercontent.com/1952838/59940143-334a8500-945a-11e9-9d7b-bd393d72d01e.png)

**It takes an average of 10s to process a single page after only 300 pages!**

To understand what made it this slow, I ran the xdebug profiler, here is the result:

![xdebug-profile](https://user-images.githubusercontent.com/1952838/59940275-93412b80-945a-11e9-929e-fa4b367f6d98.png)

It looks like recursive calls to `Crawler::addToDepthTree()` are eating 95% of the CPU and make the crawling shockingly slow.

Before I dig further into the code (I'm not yet familiar with it), **is there any easy fix that comes to your mind, to speed this process up?**

*Note: I cannot attach the cachegrind file, as it's 2.5GB.*

**Comment by BenMorel** [comment]
I suspect that this may be the cause of the cURL timeouts I experienced in #236: spending too much time (more than the cURL timeout) in a function without calling `curl_multi_exec()` or `curl_multi_select()` could very well be the root cause.

**Comment by BenMorel** [comment]
I can confirm that the problem lies in the highly inefficient depth algorithm.

Here is the same plot with no `setMaximumDepth()`:

![plot](https://user-images.githubusercontent.com/1952838/59955919-314de980-948d-11e9-8c73-91d257b31b45.png)

After 1000 pages crawled everything is still super fast.

And my intuition was right, **I do not get the cURL timeouts mentioned in #236** anymore!

So speeding up the depth algorithm would reasonably fix both issues.

**Comment by Redominus** [comment]
Lol, I didn't remeber having this problem because almost from the second day I started using this crawler I always run it with depth tree deactivated, it is useless for what I am using the crawler.

**Comment by BenMorel** [comment]
> Lol, I didn't remeber having this problem because almost from the second day I started using this crawler I always run it with depth tree deactivated, it is useless for what I am using the crawler.

For most reasonably sized sites, I'm leaning towards doing the same thing. Limiting the depth might still be useful for very large sites though, or sites with virtually infinite crawling (think search pages with query parameters).

Anyway this feature is there, it needs to be fixed.

> Also get rid of the slow default CrawlQueue and use some indexed one. Every time you check if a url exists it does a foreach.

Yeah this hit me as well when I first saw this loop.

Also, according to the profiler, `UriInterface` to `string` conversion it eating up a lot of CPU, too.

There's a lot of room for optimization right now!

I'll see if I can come up with a PR to bring it up to speed.

**Comment by danhunsaker** [comment]
> I'll see if I can come up with a PR to bring it up to speed.

Pun intended, I'm sure. 😄

**Comment by freekmurze** [comment]
Thanks for your detailed research on this performance problem. I'd accept a non-breaking PR that fixes this.

**Comment by Redominus** [comment]
Is this issue related to #210?

**Comment by Redominus** [comment]
> Also, according to the profiler, `UriInterface` to `string` conversion it eating up a lot of CPU, too.

That one is because the depth algoritm is calling  the `UriInterface` to `string` cast operation lots of times in this foreach.
```php
        if ($node->getValue() === (string) $parentUrl) {
            $newNode = new Node((string) $url);

            $node->addChild($newNode);

            return $newNode;
        }

        foreach ($node->getChildren() as $currentNode) {
            $returnNode = $this->addToDepthTree($url, $parentUrl, $currentNode);

            if (! is_null($returnNode)) {
                break;
            }
        }
```

**Comment by BenMorel** [comment]
> Is this issue related to #210?

Totally! I missed this issue, thanks for bringing it to my attention. I was preparing a fix that is very similar to @joaomisturini's when your message arrived.

I'm also getting rid of `nicmart/tree` which is totally useless here: every time the depth of a URL is needed, the code recursively loops through the tree to find the correct node, instead of just using a lookup array (or storing the depth directly in the `CrawlUrl`, which is an alternative approach).

@freekmurze's Regarding your [comment](https://github.com/spatie/crawler/pull/210#issuecomment-485565686) on the linked issue:

> I've decided to not pull this in for now, but when we create a new major version of the crawler. That'll probably happen when PHP 7.4 is released.

I could PR a non-breaking fix, but it will not be pretty. TBH I love your library, it's really well designed, but at the same time there are loads of things that could be improved but would require a good number of breaking changes.

Is there any chance you can change your mind and start preparing a v5 release right now (I'm willing to help on many points), or is there no way we can get this before the end of the year and the arrival of PHP 7.4?

On this last point, unless you're willing to only target PHP 7.4+, there's no good reason to wait until this version is released. We can right away test it against the alpha (Travis has been supporting `7.4snapshot` for a while!) and make it forward-compatible with PHP 7.4.

What do you think?

**Comment by freekmurze** [comment]
Currently I have very little time to work on this myself. Outside of fixing the performance issues, what kind of functionalities would you add to a v5?

**Comment by BenMorel** [comment]
Hi Freek,

I think a first roadmap for v5 could be:

## New features

- proper support for persistent (database-backed) queues (#137, #200), allowing to resume an interrupted crawl
  note that this would benefit a lot from #237 (putting a failed URL back onto the persistent crawl queue)
- [*optional*] ship a PDO implementation of a database-backed crawl queue, which will also serve as a reference implementation

# Fixes


## Code improvements

- Get rid of id in `CrawlUrl`: Guzzle's `Pool` [yields string keys](https://github.com/guzzle/guzzle/pull/1203) as well, we do not need an int, and can simplify the code
- Improve performance of `CollectionCrawlQueue` by using an indexed array rather than [looping through the URLs](https://github.com/spatie/crawler/blob/67974a810f6a342c333c4e348fcfad7c1375ffde/src/CrawlQueue/CollectionCrawlQueue.php#L103-L117)
- Add return types wherever possible (example: `CrawlQueue::getFirstPendingUrl() : ?CrawlUrl`)
- Change signature of `CrawlQueue::has(CrawlUrl $crawlUrl)` to be consistent with the other methods


## Cleanup

- remove deprecated methods (`Crawler::endsWith()`)

---

IMHO these improvements could push this package to the next level, allowing it to be part of larger systems that need to perform crawling on a daily basis, and not just one-shot jobs as it's currently really aimed for.

**Comment by Redominus** [comment]
> ## New features
> * proper support for persistent (database-backed) queues (#137, #200), allowing to perform a crawl in discrete steps at different points in time, and resume an interrupted crawl; note that this would benefit a lot from #237 (putting a failed URL back onto the persistent crawl queue) if you're willing to revisit this
> * [_optional_] ship a PDO implementation of a database-backed crawl queue, which would also serve as a reference implementation

Careful, not everybody persists in SQL databases. Even more, not everybody uses databases. Right now it is easy to implement a persisted crawlQueue. You just need an aditional method to load urls on startup.

> * Decouple CrawlRequestFailed|FulfilledClass from Guzzle by replacing it with an interface; this will allow better static analysis than a invokable class name, and make the contract more explicit, such as: public function crawlFailed(RequestException $exception, CrawlUrl $url)
It's a bit bizarre the approach taken right now, instead of an Interface contract.

I like the idea o yielding the Ids and more strict typing. I would add psr-2 import rules as cleanup, right now imports are ordered in ascendent string size.

**Comment by BenMorel** [comment]
> Careful, not everybody persists in SQL databases. Even more, not everybody uses databases.

Sure. But the fact that one can implement a custom `CrawlQueue` leaves the door open to such implementations, so it would be nice to provide the grounds to cover this use case fully.

> Right now it is easy to implement a persisted crawlQueue. You just need an aditional method to load urls on startup.

Then we should provide such a method, and not expect one to dig into the source code and find out how to extend the Crawler and potentially open a can of worms. And if we don't provide support for databases out of the box, I think it could help a lot to at least document how to do it, as I really think that persistent/discrete/resumable jobs is what can push the lib to the next level, as mentioned above.

> I like the idea o yielding the Ids and more strict typing. I would add psr-2 import rules as cleanup, right now imports are ordered in ascendent string size.

👍

**Comment by BenjaminHoegh** [comment]
About `v5` take a look at this [crawlzone](https://github.com/crawlzone/crawlzone)

**Comment by freekmurze** [comment]
@BenMorel those v5 things do sound good. Feel free to send a PR for this. Make sure to have everything covered with tests. Just target the `master` branch in your PR. I'll retarget it to a `v5` if it should be necessary.

**Comment by BenMorel** [comment]
@BenjaminHoegh Thanks for the link, crawlzone looks very promising, I'll keep an eye on it!

@freekmurze Amazing. Can't wait to open the first PR!

**Comment by BenMorel** [comment]
@freekmurze The problem with targeting `master` is that I'll probably update the README along the way, together with the CHANGELOG. This will reflect in the [homepage](https://github.com/spatie/crawler), which might be confusing for people coming for docs.

**Comment by freekmurze** [comment]
As long as I don't merge anything the homepage will remain the same.

**Comment by BenMorel** [comment]
Oh, I see. My suggested workflow was not to merge everything at once, but through small PRs, one at a time. This will be easier to manage and understand the changes. Hence my suggestion to branch to `v5`.

I'm preparing a separate issue for the roadmap, we can discuss this there!

**Comment by eminos** [comment]
I'm experiencing similar problems. Some crawls just continuously slow down almost to a halt.
@BenMorel did anything ever happen with this issue?
