### ISSUE TITLE
Crawl just the single page given

### ISSUE THREAD

**Issue by liamcharmer** [spatie/crawler#245]
Is it possible to just crawl the one single page that has been given?

**Comment by freekmurze** [comment]
If you want to get exactly one page, you don't need a crawler. Maybe it's better to use something like curl or guzzle.

**Comment by liamcharmer** [comment]
> If you want to get exactly one page, you don't need a crawler. Maybe it's better to use something like curl or guzzle.

Only issue i'm having is that I need to get the pages after they have loaded and with JavaScript to get the content, I saw that this could potentially solve that issue

**Comment by freekmurze** [comment]
Take a look at our [Browsershot](https://github.com/spatie/browsershot) package

```
Browsershot::url('https://example.com')->bodyHtml(); 
```
