### ISSUE TITLE
Crawling gives 500 status

### ISSUE THREAD

**Issue by mihaivinaga** [spatie/crawler#248]
I'm trying to crawl this link http://www.mumbaiwebdesign.in/ and I have to following test cases:

1. I access the link thru my google chrome browser, everything's fine
2. I try use wget thru the command line, I get status 500

```
(base) ➜  ~ wget http://www.mumbaiwebdesign.in/
--2019-08-01 00:11:42--  http://www.mumbaiwebdesign.in/
Resolving www.mumbaiwebdesign.in (www.mumbaiwebdesign.in)... 202.143.99.109
Connecting to www.mumbaiwebdesign.in (www.mumbaiwebdesign.in)|202.143.99.109|:80... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2019-08-01 00:11:59 ERROR 500: Internal Server Error.
```

3. I try to use spatie/crawler, same problem, get status 500
```
Crawler::create()
        ->executeJavaScript()
        ->setCrawlObservers([new CrawlObserverV2($link)])
        ->setUserAgent('Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0')
        ->startCrawling($link);
```
4. I try to use spatie/browsershot, everything works as it should, I get a pdf with the page loaded

```
Browsershot::url($link)->save('example.pdf')
```

5. I try to use symfony/panther, the page is loaded with all the html generated

Maybe I missed a setting when installing puppeteer. Any help would be appreciated, I am trying to find a solution for crawling websites with JS and the options for this crawler look really appealing but I haven't got it to work for websites that block crawlers that dont use browsers that can load javascript.

Thanks

**Comment by Redominus** [comment]
By default wget sends the header `Accept-Encoding: identity` the server you are trying to access does not support that encoding.
try with  `wget "http://www.mumbaiwebdesign.in/" --header="Accept-Encoding:  gzip" --compression "gzip"`
The crawler is going to need to be configured with guzzlehttp options :
```php
Crawler::create([
RequestOptions::HEADERS => [
                    'Accept-Encoding' => 'gzip, deflate',
                ]
]);
```

You can check what headers your broser uses in the debugging console(F12) -> Network -> Request Headers.
