### ISSUE TITLE
hook into browsershot before HTML retrieval

### ISSUE THREAD

**Issue by Gummibeer** [spatie/crawler#257]
Is there any way to hook into browsershot before it returns the HTML except of overriding `\Spatie\Crawler\Handlers\CrawlRequestFulfilled::getBodyAfterExecutingJavaScript()`?

Usecase would be something like: click a "more" button on a list page until there is no "more" button. Or scroll several times on an endless scroller. Or click on a content toggle to load async content.

Atm I've done it by overriding the named method:
```php
protected function getBodyAfterExecutingJavaScript(UriInterface $url): string
{
    $browsershot = $this->crawler->getBrowsershot();

    $browsershot->setUrl((string) $url);
    $browsershot->evaluate('window.scrollBy(0, document.body.scrollHeight)');

    $html = $browsershot->bodyHtml();

    return html_entity_decode($html);
}
```

But this doesn't feel right.

**Comment by brendt** [comment]
This might be a good feature to have in browsershot, which then can be used in the crawler package: event hooks. I'll make an issue for it: https://github.com/spatie/browsershot/issues/329

**Comment by MichaelNino** [comment]
The issue created goes to a invalid URL at: https://github.com/spatie/browsershot/issues/329

**Comment by brendt** [comment]
This one is almost 2 years old, I don't know what that issue is about anymore. Maybe a search on browsershot could help you out?
