### ISSUE TITLE
not able to find a function to return all founded urls from the first base URL crawl

### ISSUE THREAD

**Issue by parthsynup** [spatie/crawler#258]
I have input as a base URL. And need to get all the host URL links present in the base URL web page. The crawler is returning the links only after crawling them one by one which is taking more time. Where can we get all the URLs without crawling them just to list them down?

**Comment by freekmurze** [comment]
If you need to get all links from a page, you could opt to use Symfony's DomCrawler:
https://symfony.com/doc/current/components/dom_crawler.html
