### ISSUE TITLE
Is it possible to modify the URL to be crawled?

### ISSUE THREAD

**Issue by mw108** [spatie/crawler#259]
Is it possible to modify the URL, which will be crawled, for instance, add "index.php" at the end of the URL?

URL to be crawled: https://test.mysite.com/my-uri/
Modified URL that should be crawled instead: https://test.mysite.com/my-uri/index.php

**Comment by freekmurze** [comment]
Though I've never used it that way, I think you can modify the url that's being passed to `willCrawl` of a crawl observer. Check the docs to learn how to create a a custom crawl observer.

**Comment by codealfa** [comment]
Could we look back at this? What you are passed is an instance of `Psr\Http\Message\UrInterace`, which is immutable and `willCrawl` doesn't return any values so there's no easy way to modify the URL. This feature would be useful. Thanks.
