### ISSUE TITLE
302 Redirects?

### ISSUE THREAD

**Issue by amousavii** [spatie/crawler#263]
How to continue to a page that gets status code 302 and redirected?

**Comment by Redominus** [comment]
When instantiating the crawler you can pass guzzlhttp client options. You would need to pass the option to follow redirects.
```php
Crawler::create([RequestOptions::ALLOW_REDIRECTS => true]);
```
or if you want to track them and have the redirects in a response header:
```php
Crawler::create([
RequestOptions::ALLOW_REDIRECTS => [
                'track_redirects' => true,
            ],
]);
```
