### ISSUE TITLE
Response Code 403

### ISSUE THREAD

**Issue by yousefrastgar** [spatie/crawler#265]
Hi, Thanks for creating this useful package,
some urls return status code 403 in response, and then after 5 seconds will redirect client to the destination page. it seems that they do this to prevent being crawled or requested by robots. how can I handle this?
for example forcing the crawler to stay on the 403 page and then follow the redirection to get the correct response?
ex: https://www.scorptec.com.au/product/Network-Storage-(NAS)/1-4-Bays/70387-DS418Play

another problem is, some of the page content are loaded after the document is ready (for example by ajax request). how to make the crawler wait for fully load of page's content?
ex: https://www.shoppingexpress.com.au/buy/synology-diskstation-ds418play-2gb-4-bay-4k-stream/DS418Play

**Comment by Redominus** [comment]
When testing pages try them from your browser with javascript deactivated.
The first one returns a 503 with a javascript challenge. They are probably using some type on WAF. In fact you can see a gem like: 
![image](https://user-images.githubusercontent.com/22024214/67579617-1b0aaf80-f745-11e9-80c1-ccbd27af3c3a.png)
Maybe you could have some luck using the javascript capabilities of the crawler(browsershot). 
Any javascript(i.e:document ready) is going to need also browsershot. Be carefull with google, using your own ip for large amounts of data scrapping will end with your ip score reduced.
PS: You can check your reCaptcha score [here](https://recaptcha-demo.appspot.com/recaptcha-v3-request-scores.php)

**Comment by yousefrastgar** [comment]
thanks alot @Redominus

**Comment by Calbo67** [comment]
@yousefrastgar Did you ever sort this? I'm trying to crawl a site and it returns a 403 response.
