### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by ClaudiuTodosia** [spatie/crawler#270]
I have a small issue with this crawler, maybe someone can help me. I have this code:
        Crawler::create()
            ->setCrawlObserver(new CrawlerHelper($fileName))
//            ->setMaximumCrawlCount(30)
            ->ignoreRobots()
            ->startCrawling($domain);

and the CrawlerHelper
<?php
namespace App\Helpers;

use DOMDocument;
use Illuminate\Console\Command;
use Spatie\Crawler\Crawler;
use \Spatie\Crawler\CrawlObserver;
use Psr\Http\Message\UriInterface;
use Psr\Http\Message\ResponseInterface;
use GuzzleHttp\Exception\RequestException;

class CrawlerHelper
{
    private $pages = [];
    private $fileName = '';
    private $links = [];

    public function __construct($url)
    {
        $this->fileName = $url;
    }

    public function willCrawl(UriInterface $uri)
    {
        echo "Now crawling: " . (string)$uri . PHP_EOL;
        $this->links[] = (string)$uri . PHP_EOL;
    }

    public function crawled(UriInterface $url, ResponseInterface $response, ?UriInterface $foundOnUrl = null)
    {
            if ($response) {
                $path = $url->getHost();
                $doc = new DOMDocument();
                @$doc->loadHTML($response->getBody());
                $this->pages[$path] = $path;
            }
    }

    public function crawlFailed(UriInterface $url, RequestException $requestException, ?UriInterface $foundOnUrl = null)
    {
        return 'failed';
    }

    public function finishedCrawling()
    {
        \Storage::disk('local')->put($this->fileName, serialize($this->links));
    }
}
and I get this error: "Status code must be an integer value between 1xx and 5xx." for some sites, not all of them. But if I set the setMaximumCrawlCount to 30 or a lower value then will work, but on other sites I need the maximum crawler to be bigger. What I'm doing wrong?

**Comment by freekmurze** [comment]
Please format your question and provide a descriptive title. For help with uses of this package, turn to a public forum like stackoverflow.
