### ISSUE TITLE
Is there any way to crawl a web page which is login protected ?

### ISSUE THREAD

**Issue by NishantSoni** [spatie/crawler#275]
Using this package, i want to call login page with the required email & paswrd, after that, i want to crawl another page which will open after successfully login.

**Comment by Redominus** [comment]
If the session is stored in a cookie:

1. Create a guzzle client with cookies config. 
2. Make the login request with the client.
3. Create the crawler with the previously used guzzle client.
4. Start crawling in the page you want.

Hope it helps!

**Comment by NishantSoni** [comment]
Thanks @Redominus , step-1 & 2 is working fine, but how to pass previous guzzle client while creating the crawler ? some thing like this -> 

```
$jar = new CookieJar();
$client = new \GuzzleHttp\Client(['cookies' => true]);
$response = $client->request('POST', 'url', [
                    'json' => [
                        'username' => 'username',
                        'password' => 'pwd'
                    ],
                    'headers'  => [
                        'Accept' => 'application/json',
                        'Content-Type' => 'application/json',
                    ],
                    'cookies' => $jar
                ]
            );

Crawler::create(['cookies' => $jar])
->setMaximumCrawlCount(5)
->setCrawlObserver($crawlerIndex)
->startCrawling($url);
```
Or in some other way ?

**Comment by Redominus** [comment]
Instead of using the static constructor use the normal constructor method which is public and allow you to pass a client :D.
