### ISSUE TITLE
Multiple domains

### ISSUE THREAD

**Issue by gdandersson** [spatie/crawler#278]
I've got my own profile set by setCrawlProfile() but if I try to crawl two different domains at the same time, it doesn't even get to shouldCrawl().

From Handlers/CrawlRequestFulfilled.php:
`        if (! $this->crawler->getCrawlProfile() instanceof CrawlSubdomains) {
            if ($crawlUrl->url->getHost() !== $this->crawler->getBaseUrl()->getHost()) {
                return;
            }
        }
`

If I comment `return;` it works fine.

Any plan on adding "ignore baseUrl" as an option?

**Comment by freekmurze** [comment]
No plans for that. However, you can submit a PR with tests and an updated readme. If the code that allows this is simple enough, I'll consider adding it to the package.
