### ISSUE TITLE
Crawler skips both success and fail methods.

### ISSUE THREAD

**Issue by koentjeh** [spatie/crawler#284]
While crawling microsoft.com the willcrawl() and finishedCrawling() executes but skips both crawled() and crawlFailed(). It's likely to be because Microsoft detected a bot yet it's impossible to detect what actually happened.

**Comment by brendt** [comment]
Have you tried setting another user agent? https://github.com/spatie/crawler#using-a-custom-user-agent

**Comment by koenhoeymans** [comment]
I had the same problem and no errors/warnings given. The issue disappeared when enabling the curl extension in the test environment.
