### ISSUE TITLE
How to store crawled links in database and how to use crawlQueue?

### ISSUE THREAD

**Issue by milanchheda** [spatie/crawler#304]
Hey, thanks for the excellent package. 

I have an application, where the user would enter the URL and the application would crawl the respective URL and provide the result to the user.

1. When user enters the URL, application stores it in the database
Example: 
```php
$website = WebsitesToCrawl::create([
    'url' => $this->url
]);
````
So, the application knows that following user has requested to crawl following URLs.

2. As soon as, above is saved, application dispatches a job and job starts crawling the links. So right after above line, we have:
```php
CrawlWebsite::dispatch($website)->onQueue('abc-xyz');
```

3. Inside the ```CrawlWebsite```, we have:
```php
Crawler::create()
            ->setCrawlObserver(new SiteCrawlObserver())
            ->setMaximumResponseSize(1024 * 1024 * 2)
            ->startCrawling($this->website->url);
```

Questions:
1. when the crawling is done, ```SiteCrawlObserver``` will give the results, but how do I know which URL was getting crawled? As in, can I pass respective table id or some reference? This reference is important, as there can be a case where 2 users entered the same URL to crawl. So, in database it would have different records, different times. Any pointers to this would be much appreciated. 
2. How to use ```crawlQueue```? Is there an example or some reference to understand how to use crawlQueues?

Thanks again for the great package.

**Comment by asjsrep** [comment]
@milanchheda if you haven't found the solution already. You can change your implementation of SiteCrawlObserver to do what you want. You can either pass in an ID to the constructor or generate a UUID in the constructor of your SiteCrawlObserver class. Then when you save or return your results include your UUID.

If you look at the abstract class Spatie\Crawler\CrawlObserver the  crawled method is passed UriInterface $url, that's the current url you're crawling you can get the URL by casting it to a string: (string) $currentUrl

As for the CrawlQueue there are a couple of implementations array and redis linked to in the docs. They should help show you how it's implemented

**Comment by milanchheda** [comment]
Thanks @asjsrep. That helped and resolved my problem.

Would you know how to get total number of URLs before starting to crawl all the links? Basically, to show there are X number of urls that would be crawled and incrementally they get crawled and count decreases to 0.

Thanks again. 🙏

**Comment by asjsrep** [comment]
@milanchheda no problem. 

The number of pending URLs is going to fluctuate during the crawl as new pages are discovered. Unless you're just doing a one page crawl you won't be able to tell the total number of URLs at the beginning. But to show a running count of URLs you can either log it in you CrawlObserver->crawled method (increment a DB count, raise an event etc) or you can implement your own Queue and handle your reporting in the add and markAsProcessed methods.
