### ISSUE TITLE
Form-Action?

### ISSUE THREAD

**Issue by Defcon0** [spatie/crawler#315]
Hello,

at first: thanks for the great module. I just installed it and it worked like a charm :+1: 

I only stumbled over one thing:

When I look inside the Crawler class, I can see that the main element for it is the `a` element which makes perfect sense.

But what about form actions? Aren't these also redirects which the crawler should follow? Or do you skip them because you'd like to "submit" them in order to have a useful redirect page because of the get/post context?

My use case is success pages from contact forms.

Thanks in advance for clearification.

Bye Defcon0

**Comment by freekmurze** [comment]
A crawler should imho not follow form actions. It's highly likely that servers will respond with some kind of error when trying to submit something.

**Comment by Defcon0** [comment]
I assumed that ;-) Thanks for the fast reply.
