### ISSUE TITLE
how to know when a link is found for the second/third... time?

### ISSUE THREAD

**Issue by bobemoe** [spatie/crawler#336]
I have a use case for a CrawlObserver to know when a link is found **again**:
* Count the number of times a link is found
* Collate all the `foundOnUrl`s for a given link

I created PR #280 which I am still using as a patch in my project, but it got closed stale and I cant reopen it.

**Comment by freekmurze** [comment]
That PR contains a breaking change, so I'm not going to merge it in for now. I'll reconsider this when creating a new major version.

**Comment by bobemoe** [comment]
Sure. Is it worth keeping it open? looks like its already missed a major release since I submitted it.

If you'd like any help just give me a shout.

Thanks.

**Comment by freekmurze** [comment]
@bobemoe I've just created the `v6` branch where the next major version can be prepared. Feel free to send a PR with the proposed functionality to that branch, make sure to include an updated readme and tests.
