### ISSUE TITLE
"The promise was rejected" Exception

### ISSUE THREAD

**Issue by flmommens** [spatie/crawler#353]
Hi,
I'm using spatie/crawler 4.7.5 with php 7.2

Running the crawler I get after a few URL the exception:

```
In Create.php line 62:
The promise was rejected with reason: Invoking the wait callback did not resolve the promise  
```

**Comment by flmommens** [comment]
May I have an explanation?

**Comment by freekmurze** [comment]
Could you create a minimal app that has an example where this problem occurs?

**Comment by flmommens** [comment]
Use the code from this issue https://github.com/spatie/crawler/issues/353
This happened only a few times when my connexion wasn't good. So might be linked to timeouts or connexion drops.

**Comment by comes** [comment]
same here:

`$baseUrl = 'https://www.linde-mh.sk';
    Crawler::create()
        ->setCrawlObserver(new \App\Crawler\InterestCrawler($dataStorage))
        ->setCrawlProfile(new \Spatie\Crawler\CrawlProfiles\CrawlInternalUrls($baseUrl))
        ->setDelayBetweenRequests(300)
        ->acceptNofollowLinks()
        ->setParseableMimeTypes(['text/html', 'text/plain'])
        ->setMaximumDepth(3)
        ->startCrawling($baseUrl);`

**Comment by sataris** [comment]
I'm also experiencing this issue. 

Here's a stacktrace, 

```
PHP Fatal error:  Uncaught GuzzleHttp\Promise\RejectionException: The promise was rejected with reason: Invoking the wait callback did not resolve the promise in /var/www/html/redacted/vendor/guzzlehttp/promises/src/Create.php:62
Stack trace:
#0 /var/www/html/redacted/vendor/guzzlehttp/promises/src/Promise.php(72): GuzzleHttp\Promise\Create::exceptionFor()
#1 /var/www/html/redacted/vendor/spatie/crawler/src/Crawler.php(477): GuzzleHttp\Promise\Promise->wait()
#2 /var/www/html/redacted/vendor/spatie/crawler/src/Crawler.php(426): Spatie\Crawler\Crawler->startCrawlingQueue()
#3 /var/www/html/redacted/src/CrawlerService.php(65): Spatie\Crawler\Crawler->startCrawling()
#4 /var/www/html/redacted/vendor/Redacted/redacted/src/Service.php(572): Redacted\CrawlerService->processSuccess()
#5 [internal function]: Redacted\Service->callback()
#6 /var/www/html/redacted/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php(1044): call_user_func()
#7 in /var/www/html/redacted/vendor/guzzlehttp/promises/src/Create.php on line 62
```

I think you need to catch the exception thrown in https://github.com/spatie/crawler/blob/7df48888d0dcc5d9f1175847224147c8bce34f70/src/Crawler.php#L477

I don't know enough about your codebase to make a PR, but if you want to recreate it, I think creating a test and putting a sleep  somewhere should be enough to trigger it.

**Comment by comes** [comment]
Hej,

as a workaround I did this:

```
class CrawlWebsite implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels, Batchable;

    protected $url;

    /**
     * Create a new job instance.
     *
     * @param string $url
     */
    public function __construct(string $url)
    {
        $this->url = $url;
    }

    /**
     * Execute the job.
     *
     * @return void
     */
    public function handle()
    {
        if ($this->batch()->cancelled()) {
            // Determine if the batch has been cancelled...

            return;
        }

        $queueDriver = new CacheCrawlQueue($this->url, config('crawler-toolkit.cache_ttl', 3600));

        Crawler::create()
            ->setCrawlObserver(new \App\Crawler\InterestCrawler($this->batchId))
            ->setCrawlProfile(new \Spatie\Crawler\CrawlProfiles\CrawlInternalUrls($this->url))
            ->setDelayBetweenRequests(300)
            ->acceptNofollowLinks()
            ->setCurrentCrawlLimit(5)
            ->setConcurrency(1)
            ->setParseableMimeTypes(['text/html', 'text/plain'])
            ->setMaximumDepth(3)
            ->setCrawlQueue($queueDriver)
            ->startCrawling($this->url);

        if ($queueDriver->hasPendingUrls()) {
            $this->batch()->add([
               new self($this->url)
            ]);
        }
    }
}

```

I put everything in a job
I set `setConcurrency` to 1 and crawl only a few domains. after n crawls, it ends. With the help of a queue driver, I re-dispatch the job until no pages are left.

works for me.

**Comment by eminos** [comment]
I'm having the same issue. 
I don't know what is causing it but it happens every time after a while crawling this website: 
www . univerzalno . com

**Comment by sataris** [comment]
@comes  suggestion above does help, one thing I have noticed is that this seems to only trigger when 

`executeJavascript()` is used.

**Comment by flmommens** [comment]
No, I wasn't using it when I got the exception.
