### ISSUE TITLE
Can't install with Laravel 8.57

### ISSUE THREAD

**Issue by morawcik** [spatie/crawler#374]
Hi,

When I'm trying install package I'm getting error:

> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - spatie/crawler[7.0.0, ..., 7.0.1] require guzzlehttp/psr7 ^1.8 -> found guzzlehttp/psr7[1.8.0, 1.8.1, 1.8.2, 1.x-dev] but the package is fixed to 2.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
>     - Root composer.json requires spatie/crawler ^7.0 -> satisfiable by spatie/crawler[7.0.0, 7.0.1].

Steps to reproduce:

1. `laravel new test`
2. `cd test`
3. `composer require spatie/crawler`

**Comment by KhacSonNguyen** [comment]
just do it: 
- composer require guzzlehttp/psr7:2.0.0
- composer require spatie/crawler

**Comment by MmKargar** [comment]
@lesaff 
you have to downgrade guzzlehttp/psr7 from 2.1.0 to 1.8.3
```
composer require guzzlehttp/psr7 ^1.8.3
composer require spatie/crawler
```

**Comment by devvictorvincent** [comment]
even composer require guzzlehttp/psr7 ^1.8.3 fails on laravel 9. any help on how i can resolve this issue?
