### ISSUE TITLE
Laravel and Vapor

### ISSUE THREAD

**Issue by Andrew-Hike** [spatie/crawler#377]
Laravel Vapor uses alpine linux. which does not natively support pupeteer/browsershot

Please update the DOCUMENTATION for this package with either instructions to install pupeteer, or let people know that if you set enableJavascript() when initiating a crawl that laravel/vapor:php80 docker images will not work correctly, as alpine-linux does not have a stable chromium release that will work.

if you do enableJavacript()

You'll either get an error, or BrowserShot will return true and only crawl a single page.

JUST update DOCUMENTATION, to let peple know so they dont have to waste 2/3 days to find out nothing can fix this issue with laravel Vapor () its vapors fault for having an ali[pine based Docker image)

**Comment by freekmurze** [comment]
Feel free to send a PR to the docs.
