### ISSUE TITLE
http referer of the crawled url

### ISSUE THREAD

**Issue by aimagician** [spatie/crawler#378]
Hello

Can I get an HTTP referer of the crawled URL, in this case, it is the parent URL?

- parent page
     - first child page(FCP)
         - child page (i am crawling child page, I need an URL of the FCP)

Thank you

**Comment by Redominus** [comment]
As you can check https://github.com/spatie/crawler/blob/9596cd0c9e8d61ab31ab5d9bd961b2671323bba5/src/CrawlObservers/CrawlObserver.php#L27-L31
An observer receives the url where the current url was found. You could create an observer to store this data.
