### ISSUE TITLE
"RequestOptions::COOKIES => true" can lead to PHP Warnings

### ISSUE THREAD

**Issue by rbrecht** [spatie/crawler#42]
Hey guys,

I was playing around with your crawler. After using it on several domains, I noticed this warnings in my terminal: "PHP Warning:  strpos(): Empty needle in /var/www/scanner/vendor/guzzlehttp/guzzle/src/Cookie/SetCookie.php on line 315"
Dont't had the time to dig further into this, but a "RequestOptions::COOKIES => false" solved the warnings. 
Unfortunately I cannot tell you on which domain this appeared exactly. 
Why should you need cookies anyway on a crawler?

kindly regards

**Comment by freekmurze** [comment]
Thanks for letting us know. You can [pass client options via the create method](https://github.com/spatie/crawler/blob/master/src/Crawler.php#L40).
