### ISSUE TITLE
Network.getAllCookies

### ISSUE THREAD

**Issue by futureweb** [spatie/crawler#426]
Hey there,

as I'm just updating my GDPR Cookie Crawler ... possible to get my old Changes live?
https://github.com/spatie/browsershot/pull/350
If they are still working with current Version ... haven't had the time to check yet ...

Andy

**Comment by MaxKutsayev** [comment]
+1

**Comment by futureweb** [comment]
I would re-open it as it's still important ... but it seems I can't reopen it?!?
@freekmurze
