### ISSUE TITLE
Call to undefined method GuzzleHttp\Client::getConfig()

### ISSUE THREAD

**Issue by tommusrhodus** [spatie/crawler#434]
Hi!

Using this tool in a WordPress plugin and I'm running into the following error:

> `Call to undefined method GuzzleHttp\Client::getConfig()`

This is due to GuzzleHttp being included in another plugin using the updated version, noting this docBlock from the currently used GuzzleHttp version: `@deprecated Client::getConfig will be removed in guzzlehttp/guzzle:8.0.`

To resolve the conflict, the GuzzleHttp dependency in Crawler will need updating.

**Comment by freekmurze** [comment]
Feel free to send a PR that fixes this.
