### ISSUE TITLE
Add a execution time limit in Crawler::reachedCrawlLimits

### ISSUE THREAD

**Issue by VincentLanglet** [spatie/crawler#479]
Hi, currently the  Crawler::reachedCrawlLimits only works with a count of crawl as limit.

Sometimes it could be interesting to have a time limit to avoid having the process running for too long.

Would you be interested in such feature @freekmurze ?

Thanks

**Comment by freekmurze** [comment]
Sure, if the feature is simple code wise, and well tested, I'd consider merging it in.
