### ISSUE TITLE
relative urls bugs!

### ISSUE THREAD

**Issue by koenigseggposche** [spatie/crawler#52]
The normalizeUrl() function in Crawler.php has not been implemented properly for the reason of :

A relative url in a page has infinite absolute url representation in relative-to-absolute transformation according to RFC1808. It varies according to current page url.

For example:
The current url is:
http://www.example.com/a/b.html,
and there is anchor:
href="c.html",
According to current normalizeUrl function, the anchor will be normalize to url:
http://www.example.com/c.html,
But it's wrong, it should be:
http://www.example.com/a/c.html

**Comment by freekmurze** [comment]
Could you PR a failing test that demonstrates the bug?

**Comment by barryvdh** [comment]
The DomCrawler has logic built in to create crawlable links, as long as you pass along the current uri: http://symfony.com/doc/current/components/dom_crawler.html#links

So extracting links could be something like this: 

```php
return collect($domCrawler->filter('a')->links())
	->map(function ($url) {
		return $link->getUri();
	});
```

And you don't have to normalize it yourself.

(Disclaimer; did not test this at all, as I don't use this library, so could be that you didn't do this for a reason)

**Comment by freekmurze** [comment]
Thanks, I'll take a look at this soon

**Comment by barryvdh** [comment]
This is what I meant: #55

**Comment by halfer** [comment]
Thanks for this thread and fix. I can confirm this is still a bug in the 1.3.* release, but I have upgraded to 2.* and it is fine. Is it worth backporting to 1.3? PHP 5.6 still has ~20 months of sec support left, but Crawler 2.* requires PHP 7.
