### ISSUE TITLE
inlineJavascript 

### ISSUE THREAD

**Issue by SimZal** [spatie/crawler#6]
Hello,

I'm using your fine code and I've noticed that it doesn't seem to handle inline javascript.
Try these two lines in artisan tinker:

use \Spatie\Crawler\Url;
(new Url('javascript:linkTo_UnCryptMailto(\'iwehpk6cbq:bqWckr:oe\');'))

Possible fix in url.php:
    /**
     * Determine if this is an inline javascript
     *
     * @return bool
     */
    public function isJavascript()
    {
        return $this->scheme === 'javascript';
    }

..and then use this method to filter out these links.

**Comment by freekmurze** [comment]
Yup, looks like a good and necessary change. I'll fix this as soon as I have the time. If you need this soon, submit a PR.

**Comment by freekmurze** [comment]
Fixed by @JolitaGrazyte in version 1.2.1 of the package.
