### ISSUE TITLE
Loop

### ISSUE THREAD

**Issue by siyahmadde** [spatie/crawler#60]
Hi,
I think I experienced, crawler went into a loop.

Is there any easy way that we can prevent crawling pages that has been already crawled?

**Comment by freekmurze** [comment]
In normal circumstances this shouldn't happen.

Could you provide a clear example of when the crawler goes into a loop?

**Comment by siyahmadde** [comment]
Sure, it might be my misunderstanding though. I'm rerunning the crawler with verbose logs. I'll let you know. Thanks for the quick reply

**Comment by siyahmadde** [comment]
The issue was because of the website, I fixed it adding additional conditions in shouldCrawl method. It is my bad and thanks.
