### ISSUE TITLE
Cant get crawler to work

### ISSUE THREAD

**Issue by shoutweb** [spatie/crawler#62]
I don't do alot of object oriented PHP, so I apologize in advance, but I'm sure others who want to test out this repo may have the same question. 

I have installed the composer library and below is my code

The spatie library is at vendor/crawler/spatie relative to where this code is. I keep getting the following error. 

Fatal error: Uncaught Error: Class 'Crawler' not found in C:\xampp\htdocs\crawler2\index.php:7 Stack trace: #0 {main} thrown in C:\xampp\htdocs\crawler2\index.php on line 7

Any chance you could help?

<?php
require('vendor/autoload.php');
$url ='cnn.com';

Crawler::create()
    ->setCrawlObserver('\Spatie\Crawler\CrawlObserver')
    ->setConcurrency(1) //now all urls will be crawled one by one
    ->startCrawling($url);

**Comment by freekmurze** [comment]
It seems like you have not installed the package correctly. Try installing it in a fresh projects. If it does not work reopen this issue with instructions on how to recreate the problem.

**Comment by mcmc4519** [comment]
I have same error
@shoutweb, are you resolved this problem?

**Comment by shoutweb** [comment]
@mcmc4519 honestly can’t remember but freek comment was probably accurate I would download the zip and manually require its parameters
