### ISSUE TITLE
Handling 301 redirects

### ISSUE THREAD

**Issue by joetito1** [spatie/crawler#63]
How do you handle 301 redirects with this crawler? I have a product where people typically enter the base domain to crawl and if they enter site.com and it 301s to https://site.com the crawler stop there cold. How can I prevent this?

**Comment by freekmurze** [comment]
By default this package does not follow redirects. If you do want to follow redirects you can pass

`[RequestOptions::ALLOW_REDIRECTS => true]` to the `create`method. Those options will be passed to Guzzle.

https://github.com/spatie/crawler/blob/e3f37932d0bb72ed21edb384f8e1ad204166f1f2/src/Crawler.php#L41-L52
