### ISSUE TITLE
Depth support?

### ISSUE THREAD

**Issue by joetito1** [spatie/crawler#64]
Based on previous issues, I know you said you don't plan on implementing support for depth, but could you give any pointers on implementing this?

**Comment by freekmurze** [comment]
Not really atm, I'd have to dive in myself too to figure out how to go about it.

**Comment by joetito1** [comment]
Any chance it's something you'd consider adding now? I was going to take a stab at it, but I'm sure you could implement it a lot better since you wrote this. Just curious.

**Comment by freekmurze** [comment]
I don't need it now, so I'm not going to invest time it. I like the idea of having this in the package but I'll only pull your solution in if it feels very lightweight and is tested.

**Comment by joetito1** [comment]
Submitted a pull request including passing tests. Closing this request.
