### ISSUE TITLE
Better `CrawlProfile` interface or abstract `CrawlProfile`

### ISSUE THREAD

**Issue by AlexVanderbist** [spatie/crawler#82]
Different crawl profiles need different parameters. For example the `CrawlSubdomains` constructor expects a `$baseUrl` in the constructor whilst the `Spatie\Sitemap\Crawler\Profile` expects a callback in the constructor.

We should probably define a better `CrawlProfile` interface in the next major version of spatie/crawler or even an abstract `CrawlProfile` that can be extended and includes a way to set a base url and custom `shouldCrawl` callback on all crawl profiles.

This way we can avoid issues like https://github.com/spatie/laravel-sitemap/issues/103

**Comment by freekmurze** [comment]
We're going ahead with creating v3. There's already a `v3` branch were the new version of Browsershot is used. Let's also address this issue before tagging 3.0.0

**Comment by freekmurze** [comment]
@AlexVanderbist Could you take care of this in the coming weeks? We should probably also create a new major version of laravel-sitemap that makes use of the newly defined `CrawlProfile`.

**Comment by freekmurze** [comment]
We'll handle this on `laravel-sitemap`.
